name: Changelog Generator

on:  
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Determine whether or not to commit changelog to repo on selected branch.'
        required: true
        default: "false"
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for Git to git push
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with: 
          fetch-depth: 0
      - run: docker run -v $PWD:/workdir quay.io/git-chglog/git-chglog:0.15.1 --next-tag $(node --eval="process.stdout.write(require('./package.json').version)") --output CHANGELOG.md  
      - name: GitHub Upload Release Artifacts
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: CHANGELOG.md
          path: |
            ./CHANGELOG.md
      # publish it
      - name: Publish content
        if: ${{ github.event.inputs.publish == 'true' }}      
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./CHANGELOG.md
          git commit -m 'docs(changelog): update changelog'
          git push origin ${GITHUB_REF##*/}