#*********************************************************************
# Copyright (c) Intel Corporation 2020
# SPDX-License-Identifier: Apache-2.0
#*********************************************************************/

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
        if: ${{ matrix.node-version == '20.x' }}
      - run: npm run compile --if-present
      - run: npm test
      - name: Test Report
        uses: dorny/test-reporter@c40d89d5e987cd80f3a32b3c233556e22bdca958 # v1
        if: success() || failure() # run this step even if previous step failed
        continue-on-error: true
        with:
          name: JEST Tests # Name of the check run which will be created
          path: junit.xml # Path to test results
          reporter: jest-junit # Format of test results
          fail-on-error: "false"
      - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        name: Upload Coverage Results
        if: ${{ matrix.node-version == '20.x' }}
      - name: Rename test file
        run: mv junit.xml mps-unit-${{ matrix.node-version }}.xml
      - name: Upload JEST Results
        uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
        with:
          name: mps-unit-${{ matrix.node-version }}
          path: mps-unit-${{ matrix.node-version }}.xml
